services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - app_network
  app: 
    image: go-rest-api 
    container_name: go_rest_api
    restart: unless-stopped
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GIN_MODE=release
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - app_network
volumes:
  pgdata:
networks:
  app_network:
    driver: bridge
    